name: whatsinterface

services:
  finance-bot:
    container_name: finance-bot-app
    build:
      context: ../../
      dockerfile: devops/docker/Dockerfile.app
    ports:
      - "80:80"
    volumes:
      - ../../src:/app
    env_file:
      - ../../.env
    depends_on:
      postgres:
        condition: service_started
    networks:
      - finance-bot-network

  postgres:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.postgres
    container_name: financial_bot_postgre
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
      POSTGRES_DB: finance_bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - finance-bot-network
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiZDg1YzAwM2I4ODUyMWZlY2FmNjI0NTlkOWRlMGM1NDIiLCJ0IjoiZWMzYzNkY2MtNzhlMy00YTI0LTkzMzAtNzMwNDk3NzJkODg2IiwicyI6IlpUaGlaR1l4TTJRdE5tUTFOUzAwWWpCakxUZ3pZVEF0TURZNU9HTTNaVFppT1RZMCJ9
    restart: unless-stopped
    networks:
      - finance-bot-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  finance-bot-network:

volumes:
  postgres-data:
    driver: local
